#!/bin/bash
# Project: Authera Game Server Installer - ElewonOS
# Authera Version: v0.0.1
# License: MIT, see LICENSE.md
# Website: https://elewon.net

# DO NOT EDIT THIS FILE
# https://elewon.net


#Error output
function handle_error {
    echo -e "${GRAY}[${YELLOW}ALERT${GRAY}] ${RED}ERROR: Command failed -> '${BASH_COMMAND}' (line: ${BASH_LINENO[0]})${RESET}"
}
trap handle_error ERR
set -e
#Error output FINISH

#We pull the colour codes from this url.
source <(curl -sSL https://github.com/ElewonOS/Authera/blob/main/beacol/color.sh)
#It reads as follows
source <(curl -sSL https://github.com/ElewonOS/Authera/blob/main/repo/repo.sh)
#For convenience when developing the script, we pull things like file path etc. from the remote server.
#This allows simple development and quick position adjustments with a centralised system. You may want to update the file at this url during development.




#Installation of necessary files and update, upgrade
if [ ! -d "$AUTHERA_BASE_DIR" ]; then
    echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}$AUTHERA_BASE_DIR directory not found, creating...${RESET}"
    sudo mkdir -p "$AUTHERA_BASE_DIR"
    if [ $? -eq 0 ]; then
        echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Success: $AUTHERA_BASE_DIR created successfully.${RESET}"
    else
        echo -e "${GRAY}[${RED}ERROR${GRAY}] ${LAVENDER_GRAY}The directory $AUTHERA_BASE_DIR could not be created. Check permissions or try creating it manually.${RESET}" >&2
        exit 1
    fi
else
    echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${GREEN}$AUTHERA_BASE_DIR directory already exists. Omitted.${RESET}"
fi
#Installation of necessary files and update, upgrade - FINISH.
clear
sleep 1



#Information text for installation.
echo -e "${PURPLE}
          _    _ _______ _    _ ______ _____            
     /\  | |  | |__   __| |  | |  ____|  __ \     /\    
    /  \ | |  | |  | |  | |__| | |__  | |__) |   /  \   
   / /\ \| |  | |  | |  |  __  |  __| |  _  /   / /\ \  
  / ____ \ |__| |  | |  | |  | | |____| | \ \  / ____ \ 
 /_/    \_\____/   |_|  |_|  |_|______|_|  \_\/_/    \_\
                                                        
                                                        
"
echo -e "${GRAY}- By ${CYAN}ElewonOS${RESET}"
echo "-------------------------------------------"

echo -e "${LAVENDER_GRAY}"
echo "┌─────────────────────────────────────────────┐"
echo "│ 🔧  Select the type of game server you want to set up:"
echo "├─────────────────────────────────────────────┤"
echo "│  Unturned                                   │"
echo "│  Minecraft                                  │"
echo "│                                             │"
echo "│  Uninstall                                  │"
echo "│  Exit                                       │"
echo "└─────────────────────────────────────────────┘"
echo -e "${RESET}"
echo ""
read -p "Your Choice (Unturned, Minecraft or Rust):" server_type
game_type_lower_authera=$(echo "$server_type" | tr '[:upper:]' '[:lower:]')
#Information text for installation FINISH.




#Unturned server setup steps.
if [ "$game_type_lower_authera" = "unturned" ]; then
read -p "Continue with the server installation? (Y/n):" authera_approval
authera_approval_lower=$(echo "$authera_approval" | tr '[:upper:]' '[:lower:]')
if [ "$authera_approval_lower" = "y" ]; then
:
elif [ "$authera_approval_lower" = "n" ]; then
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Progress halted.${RESET}"
exit 0
else
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}You have made an invalid selection. Please enter Y(YES) or N(NO).${RESET}"
fi

#checking for a previously installed unturned server.
if [ -d $UNTURNED_DIR ]; then
echo -e "${GRAY}[${RED}ALERT${GRAY}] ${LAVENDER_GRAY}Unturned is already installed, please delete the previous server to continue the process. Deletion may result in data loss!${RESET}"
exit 1
fi
#checking for a previously installed unturned server.


#Unturned File installation steps.
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Preparing installation folders...${RESET}"
#checking for a previously installed Unturned server.
if [ -d $STEAMCMD_BASE_DIR ]; then
:
else 
mkdir -p $STEAMCMD_BASE_DIR > /dev/null 2>&1 #STEAMCMD FOLDER
fi
#checking for a previously installed STEAMCMD server.
if [ -d $UNTURNED_SERVER_DIR ]; then
:
else
mkdir -p $UNTURNED_SERVER_DIR > /dev/null 2>&1 #Unturned SERVER FOLDER
fi
#checking for a previously installed Unturned server.
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Installation folders are ready....${RESET}"
sleep 1
#Unturned File installation steps FINISH.


echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Preparing installation folders...${RESET}"
mkdir -p $UNTURNED_DIR > /dev/null 2>&1 #UNTURNED MAIN FOLDER
mkdir -p $STEAMCMD_BASE_DIR > /dev/null 2>&1 #STEAMCMD FOLDER
mkdir -p $UNTURNED_SERVER_DIR > /dev/null 2>&1 #UNTURNED SERVER FOLDER
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Installation folders are ready.${RESET}"



#Unturned required library installation steps.
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Downloading required libraries...${RESET}"
sudo dpkg --add-architecture i386 > /dev/null 2>&1
sudo apt install -y lib32gcc-s1 curl wget tar ca-certificates > /dev/null 2>&1
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Required libraries have been downloaded...${RESET}"
sleep 1
#Unturned required library installation steps FINISH.

#SteamCMD installation steps.
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Downloading SteamCMD...${RESET}"
cd $STEAMCMD_BASE_DIR > /dev/null 2>&1
if [ ! -f steamcmd.sh ]; then > /dev/null 2>&1
    wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz > /dev/null 2>&1
    tar -xvzf steamcmd_linux.tar.gz > /dev/null 2>&1
    echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}SteamCMD has been downloaded...${RESET}"
else
    echo -e "${RED}SteamCMD already exists, it is skipped.${RESET}"
fi
sleep 1
#SteamCMD installation steps FINISH.

#Setting up Unturned server.
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Downloading Unturned server, Please wait! (AppID: $GAME_APP_ID_UNTERMED)...${RESET}"
echo -e "${GRAY}"
$STEAMCMD_BASE_DIR/steamcmd.sh +login anonymous +force_install_dir $UNTURNED_SERVER_DIR +app_update $GAME_APP_ID_UNTERMED validate +quit
echo -e "${RESET}"
cd $UNTURNED_SERVER_DIR > /dev/null 2>&1
sudo wget $UNTURNED_START_URL > /dev/null 2>&1
sudo chmod +x $UNTURNED_START_FILE > /dev/null 2>&1
cd $UNTURNED_DIR > /dev/null 2>&1
sudo wget $UNTURNED_UPDATE_URL > /dev/null 2>&1
sudo chmod +x $UNTURNED_UPDATE_FILE > /dev/null 2>&1
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}The Unturned server has been downloaded successfully.${RESET}"
sleep 1
echo
echo -e "${RED}----------------------------------------------------------${RESET}"
echo -e "${GRAY}[${YELLOW}INFO${GRAY}]${GREEN} To start the server:${RESET}"
echo
echo -e "${LAVENDER_GRAY}cd $UNTURNED_SERVER_DIR${RESET}"
echo -e "${LAVENDER_GRAY}./$UNTURNED_START_FILE${RESET}"
echo -e "${RED}----------------------------------------------------------${RESET}"
echo -e "${GRAY}[${YELLOW}INFO${GRAY}]${GREEN} Unturned server update:${RESET}"
echo
echo -e "${LAVENDER_GRAY}cd $UNTURNED_DIR${RESET}"
echo -e "${LAVENDER_GRAY}./$UNTURNED_UPDATE_FILE${RESET}"
echo
echo -e "${GREEN}📁 To configure the server: $UNTURNED_SERVER_DIR/Servers/DefaultServer${RESET}"
#Setting up Unturned server FINISH.
#Unturned server setup steps FINISH.





#Minecraft server setup steps.
elif [ "$game_type_lower_authera" = "minecraft" ]; then
read -p "Continue with the server installation? (Y/n):" authera_approval
authera_approval_lower=$(echo "$authera_approval" | tr '[:upper:]' '[:lower:]')
if [ "$authera_approval_lower" = "y" ]; then
:
elif [ "$authera_approval_lower" = "n" ]; then
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Progress halted.${RESET}"
exit 0
else
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}You have made an invalid selection. Please enter Y(YES) or N(NO).${RESET}"
fi

#checking for a previously installed minecraft server.
if [ -d $MINECRAFT_DIR ]; then
echo -e "${GRAY}[${RED}ALERT${GRAY}] ${LAVENDER_GRAY}Minecraft is already installed, please delete the previous server to continue the process. Deletion may result in data loss!${RESET}"
exit 1
fi
#checking for a previously installed minecraft server.


read -p "Select your plugin (Craftbukkit , Spigot):" mc_jar
mc_jar_lower=$(echo "$mc_jar" | tr '[:upper:]' '[:lower:]')
read -p "Select your server version (Ex: 1.8.8):" mc_version
mc_version_lower=$(echo "$mc_version" | tr '[:upper:]' '[:lower:]')
read -p "Write the amount of ram you want to give to your server in megabits (Ex: 1024):" mc_ram


echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Preparing installation folders...${RESET}"
mkdir -p $MINECRAFT_DIR > /dev/null 2>&1 #MINECRAFT MAIN FOLDER
mkdir -p $MINECRAFT_SERVER_DIR > /dev/null 2>&1 #MINECRAFT SERVER FOLDER
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Installation folders are ready.${RESET}"



echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Downloading Minecraft server, Please wait! (Version: $mc_version_lower)...${RESET}"
cd $MINECRAFT_SERVER_DIR
sudo wget https://getbukkit.org/download/${mc_jar_lower}/${mc_jar_lower}-${mc_version_lower}.jar
sudo touch $MINECRAFT_START_FILE
echo "
#!/bin/bash 
java -Xms${mc_ram}M -Xmx${mc_ram}M --add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -jar ${mc_jar_lower}-${mc_version_lower}.jar --nogui" > $MINECRAFT_START_FILE
sudo chmod +x $MINECRAFT_START_FILE
#Minecraft server setup steps FINISH.



#Game server setup exit.
elif [ "$game_type_lower_authera" = "exit" ]; then
exit 0
#Game server setup exit FINISH.


#Server deletion steps.
elif [ "$game_type_lower_authera" = "uninstall" ]; then
clear
echo -e "${BLUE}
          _    _ _______ _    _ ______ _____            
     /\  | |  | |__   __| |  | |  ____|  __ \     /\    
    /  \ | |  | |  | |  | |__| | |__  | |__) |   /  \   
   / /\ \| |  | |  | |  |  __  |  __| |  _  /   / /\ \  
  / ____ \ |__| |  | |  | |  | | |____| | \ \  / ____ \ 
 /_/    \_\____/   |_|  |_|  |_|______|_|  \_\/_/    \_\
                                                        
                                                        
"
echo -e "${GRAY}- By ${CYAN}ElewonOS${RESET}"
echo "-------------------------------------------"

echo -e "${RED}"
echo "┌─────────────────────────────────────────────┐"
echo "│ 🔧  Select the game you want to delete:"
echo "├─────────────────────────────────────────────┤"
echo "│  Unturned                                   │"
echo "│  Minecraft                                  │"
echo "│                                             │"
echo "│  Exit                                       │"
echo "└─────────────────────────────────────────────┘"
echo -e "${RESET}"
echo ""
read -p "Your Choice (Unturned, Minecraft or Rust):" game_type
game_type_lower=$(echo "$game_type" | tr '[:upper:]' '[:lower:]')

#UNTURNED START.
if [ "$game_type_lower" = "unturned" ]; then
if [ ! -d $UNTURNED_DIR ]; then
echo -e "${GRAY}[${RED}ALERT${GRAY}] ${LAVENDER_GRAY}The Unturned server is not already installed, so we cannot continue operations!${RESET}"
exit 1
fi

read -p "Should the deletion continue? (Y/n):" authera_delete
authera_delete_lower=$(echo "$authera_delete" | tr '[:upper:]' '[:lower:]')

if [ "$authera_delete_lower" = "y" ]; then
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Unturned server deletion in progress...${RESET}"
sudo rm -r $UNTURNED_DIR
sleep 2
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Deletion completed successfully.${RESET}" 
elif [ "$authera_delete_lower" = "n" ]; then
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Deletion cancelled.${RESET}"
exit 0
else
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}You have made an invalid selection. Please enter Y(YES) or N(NO).${RESET}"
fi
#UNTURNED FINISH.



#MINECRAFT START.
elif [ "$game_type_lower" = "minecraft" ]; then
if [ ! -d $MINECRAFT_DIR ]; then
echo -e "${GRAY}[${RED}ALERT${GRAY}] ${LAVENDER_GRAY}The Minecraft server is not already installed, so we cannot continue operations!${RESET}"
exit 1
fi

read -p "Should the deletion continue? (Y/n):" authera_delete
authera_delete_lower=$(echo "$authera_delete" | tr '[:upper:]' '[:lower:]')

if [ "$authera_delete_lower" = "y" ]; then
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Minecraft server deletion in progress...${RESET}"
sudo rm -r $MINECRAFT_DIR
sleep 2
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Deletion completed successfully.${RESET}" 
elif [ "$authera_delete_lower" = "n" ]; then
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Deletion cancelled.${RESET}"
exit 0
else
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}You have made an invalid selection. Please enter Y(YES) or N(NO).${RESET}"
fi
#MINECRAFT FINISH.



#Game server deletion exit.
elif [ "$game_type_lower" = "exit" ]; then
exit 0
#Game server deletion exit FINISH.



else
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}You have made an invalid selection. Please enter Unturned, Minecraft or Rust.${RESET}"

fi
#Server deletion steps FINISH.



else
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}You have made an invalid selection. Please enter Unturned, Minecraft or Rust.${RESET}"

fi