#!/bin/bash
# Project: Authera Game Server Installer - ElewonOS
# Authera Version: v0.0.1
# License: MIT, see LICENSE.md
# Website: https://elewon.net

# DO NOT EDIT THIS FILE
# https://elewon.net

source <(curl -sSL https://raw.githubusercontent.com/ElewonOS/Authera/refs/heads/main/repo/repo.sh)


spigot-1.21.1(){

cd $MINECRAFT_DIR
sudo wget https://download.oracle.com/java/24/latest/jdk-24_linux-x64_bin.deb
sudo dpkg -i jdk-24_linux-x64_bin.deb
sleep 2
sudo rm -r jdk-24_linux-x64_bin.deb

}